services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    # depends_on:
    #   - backend
    volumes:
      - ./frontend/src:/app/src

  # backend:
  #   build: ./cms
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   environment:
  #     DATABASE_CLIENT: ${DATABASE_CLIENT}
  #     DATABASE_HOST: strapiDB
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     JWT_SECRET: ${JWT_SECRET}
  #     ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
  #     APP_KEYS: ${APP_KEYS}
  #     NODE_ENV: ${NODE_ENV}
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "1337:80"
  #   volumes:
  #     - ./cms:/opt/
  #   platform: linux/amd64

  nginx:
    build: ./nginx
    depends_on:
      - frontend
      # - backend
    restart: always
    ports:
      - "80:80"